### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by silas229** [michael-cannon/typo3-importer#8]
Hi,
after the update my whole WP Backend doesn't work anymore.
```
Fatal error: Uncaught Error: Cannot access parent:: when current class scope has no parent in /homepages/24/d22958490/htdocs/feuerwehr/wp-content/plugins/typo3-importer/typo3-importer.php:65 Stack trace: #0 /homepages/24/d22958490/htdocs/feuerwehr/wp-content/plugins/typo3-importer/typo3-importer.php(1637): TYPO3_Importer->__construct() 
#1 /homepages/24/d22958490/htdocs/feuerwehr/wp-includes/class-wp-hook.php(286): TYPO3_Importer('') 
#2 /homepages/24/d22958490/htdocs/feuerwehr/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #3 /homepages/24/d22958490/htdocs/feuerwehr/wp-includes/plugin.php(453): WP_Hook->do_action(Array) 
#4 /homepages/24/d22958490/htdocs/feuerwehr/wp-settings.php(467): do_action('init') 
#5 /homepages/24/d22958490/htdocs/feuerwehr/wp-config.php(117): require_once('/homepages/24/d...') 
#6 /homepages/24/d22958490/htdocs/feuerwehr/wp-load.php(37): require_once('/homepages/24/d...') #7 /homepages/24/d22958490/htdocs/feuerwehr/wp-admin/admin.php(31): require_once('/homepages/24/d...') 
#8 in /homepages/24/d22958490/htdocs/feuerwehr/wp-content/plugins/typo3-importer/typo3-importer.php on line 65```

**Comment by saurabhsirdixit** [comment]
@silas229 thank you for raising this issue. I am looking into this and will resolve asap. 

In the meantime you can download the older version 2.3.2 from the plugin page to move you ahead: https://wordpress.org/plugins/typo3-importer/advanced/

**Comment by alessandrobelli** [comment]
Unfortunately this is still an issue...
